### ISSUE TITLE
When restarting the game, the URI generator does not automatically show the saved overlay. (the URL isn't saved)

### ISSUE THREAD

**Issue by Zimmerson** [marzent/IINACT#71] opened 2024-01-13 15:26 UTC
Hi again,

Love the update you did with saing the URI generator being saved whenever you restart the game. Massive props to you.

Another issue has been occurring for a little while but I've never had chance to post it till now.

The URI generator defaults to Cactbot, ie this: http://proxy.iinact.com/overlay/cactbot/ui/config/config.html?OVERLAY_WS=ws://127.0.0.1:10501/ws

And since I use Kagerou, I still have to open up the list and choose Kagerou.

Would you be able to update the URI to save the URL?

Thanks!

**Comment by marzent** [comment] 2024-01-13 22:10
Yeah, just noticed...

Should be fixed with https://github.com/marzent/IINACT/commit/5a4ca889183c3be30539a8f8fffe4c257f25bfd3

Also this is a duplicate of https://github.com/marzent/IINACT/issues/70

**Closed by marzent** 2024-01-13 22:10 UTC
