### ISSUE TITLE
IINACT load error from XIV on MAC

### ISSUE THREAD

**Issue by ohgoC** [marzent/IINACT#83] opened 2024-05-25 20:52 UTC
Hi, IINACT load error has been occuring since the latest update.

I am using XIV on MAC (current OS is Sonoma 14.5). Tried re-installing it by removing repositories and adding it again, and manually removing it from local file and adding it again but no success. Could I get some help?

Following are messages that I am getting. 
<img width="661" alt="Screenshot 2024-05-25 at 1 21 32 PM" src="https://github.com/marzent/IINACT/assets/170830860/980076e7-8925-4261-8e79-29bc056e57fe">
<img width="727" alt="Screenshot_2024-05-24_at_7 00 55_PM" src="https://github.com/marzent/IINACT/assets/170830860/fd303ea3-864a-4f62-82db-3db2253e0f7e">

**Comment by eldinleb** [comment] 2024-06-02 00:52
Have the same issue.  Here's the exception from the dalamud log:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.EntryPointNotFoundException: Unable to find an entry point named 'GetThreadDpiHostingBehavior' in DLL 'USER32.dll'.

A little googling implies the problem is .Net 8 combined with the older version of Wine used by XIV on Mac:
https://forum.winehq.org/viewtopic.php?t=38337

**Comment by marzent** [comment] 2024-06-19 11:39
Duplicate of https://github.com/marzent/IINACT/issues/78

**Closed by marzent** 2024-06-19 11:39 UTC
