### ISSUE TITLE
IINACT load error on Linux

### ISSUE THREAD

**Issue by vallx-ny** [marzent/IINACT#85] opened 2024-06-16 04:24 UTC
Was working fine yesterday, but today I got my game crashing, and after the crash IINACT stopped working.

![image](https://github.com/marzent/IINACT/assets/3863005/aca80b43-a8ac-4ada-b66f-e825dac4a765)

I tried reinstalling, removing and reading the repo as well as deleting all IINACT-related files, but the error persists.

OS: Arch Linux 6.9.4 - KDE Plasma 6.0.5

Very(very very) likely the same issue as: https://github.com/marzent/IINACT/issues/83
But since that's an issue on a MAC, and I'm on Linux, I decided to open a new issue.

**Comment by AppleNectar** [comment] 2024-06-17 16:01
I think it is similar to [this](https://github.com/marzent/IINACT/issues/79)

I have the same problem.
This is due to the version of Wine, which is resolved in 9.0 or higher, so running with custom wines or Proton that are based on 9.0 or higher will resolve this issue.

If you are using the Linux native XIVLauncher, using [unofficial-wine-xiv](https://github.com/rankynbass/unofficial-wine-xiv-git) or [wine-tkg](https://github.com/Frogging-Family/wine-tkg-git) 9.0 or higher may solve the problem (although wine-tkg may not work well if you need an IME)

My environment where the problem occurs is as follows:

OS: LinuxMint 21.3
Wine frontend: Lutris 0.5.17 (Flatpak)
Wine version: wine-ge-8-26-x86_64

XIVLauncher (for Windows) is installed in the wine prefix for ffxiv.

When I changed the above wine version to Proton9-4, UMU-Proton-9.0-beta16-2, etc., IINACT worked correctly, but another problem (rare crash when opening the friends list) occurred, so I am waiting for the Wine(Proton9+) provided by Lutris provided by Lutris to solve these problems.

**Comment by vallx-ny** [comment] 2024-06-18 22:50
Honestly, this whole wineprefix thing just flies over my head and I can't make sense of most of it, even though I have many versions of it installed via ProtonUp, Lutris, and Bottles - with usually those programs managing them. I did download the unofficial-wine-xiv-valvebe-9-04 and pointed xivlauncher to it, but the launcher ignored it, then I tried swapping the files of the native wine version the launcher uses and the launcher refused to open hanging on the loader "having fun" screen.

If it's just a matter of pointing to another prefix and me being unable to do so, it's safe to close this issue I think, since it's not really the devs fault.

**Comment by AppleNectar** [comment] 2024-06-19 11:35
Anyway, the problem reported in this issue is not with IINACT itself, but with the version of the wine you are using.

I don't know if you are using the native XIVLauncher or if you are using the XIVLauncher for Windows with Lutris like me, but in any case it is possible to change the wine you are using.
(this is not something I will explain here, so please look it up)

**Comment by marzent** [comment] 2024-06-19 11:38
Duplicate of https://github.com/marzent/IINACT/issues/78

**Closed by marzent** 2024-06-19 11:38 UTC
