### ISSUE TITLE
Plugin not loading in MacOSX 

### ISSUE THREAD

**Issue by suloea** [marzent/IINACT#90] opened 2024-07-07 09:31 UTC
Below is the relavent log in dalamud.log:

2024-07-07 17:24:56.752 +08:00 [ERR] [LOCALPLUGIN] Exception in plugin constructor
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.EntryPointNotFoundException: Unable to find an entry point named 'GetThreadDpiHostingBehavior' in DLL 'USER32.dll'.
   at System.Windows.Forms.DpiHelper.DpiAwarenessScope..ctor(DPI_AWARENESS_CONTEXT context, DPI_HOSTING_BEHAVIOR behavior)
   at System.Windows.Forms.DpiHelper.EnterDpiAwarenessScope(DPI_AWARENESS_CONTEXT awareness, DPI_HOSTING_BEHAVIOR dpiHosting)
   at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Application.ThreadContext.get_MarshalingControl()
   at System.Windows.Forms.WindowsFormsSynchronizationContext..ctor()
   at System.Windows.Forms.WindowsFormsSynchronizationContext.InstallIfNeeded()
   at System.Windows.Forms.Control..ctor(Boolean autoInstallSyncContext)
   at System.Windows.Forms.ScrollableControl..ctor()
   at System.Windows.Forms.ContainerControl..ctor()
   at System.Windows.Forms.Form..ctor()
   at Advanced_Combat_Tracker.FormActMain..ctor(IPluginLog pluginLog) in /home/runner/work/IINACT/IINACT/NotACT/FormActMain.cs:line 29
   at IINACT.Plugin..ctor(IDalamudPluginInterface pluginInterface, ICommandManager commandManager, IGameNetwork gameNetwork, IClientState clientState, IDataManager dataManager, IChatGui chatGui, IPluginLog pluginLog) in /home/runner/work/IINACT/IINACT/IINACT/Plugin.cs:line 75
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 130
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 429
2024-07-07 17:24:56.803 +08:00 [INF] [LOCALPLUGIN] Finished loading ReAction
2024-07-07 17:24:56.856 +08:00 [ERR] [LOCALPLUGIN] Error while loading IINACT, failed to bind and call the plugin constructor
2024-07-07 17:24:57.237 +08:00 [INF] [LOCALPLUGIN] Finished loading DistantSeas
2024-07-07 17:24:57.239 +08:00 [INF] [PLUGINM] ============= LoadPluginsAsync(DrawAvailableAsync) END =============

**Comment by marzent** [comment] 2024-07-07 09:38
Duplicate of https://github.com/marzent/IINACT/issues/78

**Closed by marzent** 2024-07-07 09:38 UTC
